2019-06-26 12:12:41,563 ERROR: Exception on /user/susan [GET] [in /Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/isaialegria/coding_projects/flask/microblog/app/routes.py", line 72, in user
    return render_template('user.html', user=user, posts=posts)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/isaialegria/coding_projects/flask/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/isaialegria/coding_projects/flask/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/isaialegria/coding_projects/flask/microblog/app/templates/user.html", line 15, in block "content"
    <p><a href="{{ url_for('follow', username=user.username) }}">Follow</a></p>
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'follow' with values ['username']. Did you mean 'login' instead?
2019-06-26 12:18:22,384 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:44]
2019-06-26 22:15:55,813 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 12:30:46,936 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 12:46:43,179 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 12:47:47,250 ERROR: Exception on /reset_password_request [POST] [in /Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/isaialegria/coding_projects/flask/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/isaialegria/coding_projects/flask/microblog/app/routes.py", line 146, in reset_password_request
    send_password_reset_email(user)
  File "/Users/isaialegria/coding_projects/flask/microblog/app/email.py", line 17, in send_password_reset_email
    text_body=redner_template('email/reset_password.txt',
NameError: global name 'redner_template' is not defined
2019-06-27 12:48:49,800 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 12:54:37,129 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 13:00:59,047 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 13:14:45,655 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 13:15:36,259 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 13:22:53,686 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 13:24:44,742 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 13:31:15,265 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 13:39:17,819 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 15:18:19,778 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:46]
2019-06-27 16:45:51,497 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:48]
2019-06-27 19:15:24,456 INFO: Micrblog startup [in /Users/isaialegria/coding_projects/flask/microblog/app/__init__.py:50]
2019-07-02 16:22:11,470 INFO: Micrblog startup [in /mnt/c/Users/eesig/Documents/GitHub/microblog/app/__init__.py:51]
2019-07-08 08:32:19,274 INFO: Micrblog startup [in /mnt/c/Users/eesig/Documents/GitHub/microblog/app/__init__.py:70]
2019-07-08 08:36:12,622 INFO: Micrblog startup [in /mnt/c/Users/eesig/Documents/GitHub/microblog/app/__init__.py:70]
2019-07-08 08:37:05,456 INFO: Micrblog startup [in /mnt/c/Users/eesig/Documents/GitHub/microblog/app/__init__.py:70]
2019-07-08 08:44:28,591 INFO: Micrblog startup [in /mnt/c/Users/eesig/Documents/GitHub/microblog/app/__init__.py:70]
2019-07-08 08:44:59,532 INFO: Micrblog startup [in /mnt/c/Users/eesig/Documents/GitHub/microblog/app/__init__.py:70]
2019-07-08 08:45:12,401 INFO: Micrblog startup [in /mnt/c/Users/eesig/Documents/GitHub/microblog/app/__init__.py:70]
2019-07-08 08:49:58,623 INFO: Micrblog startup [in /mnt/c/Users/eesig/Documents/GitHub/microblog/app/__init__.py:70]
2019-07-08 08:51:06,439 INFO: Micrblog startup [in /mnt/c/Users/eesig/Documents/GitHub/microblog/app/__init__.py:70]
